#DATABASE
SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/usersdb?createDatabaseIfNotExist=true
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: 123456

#SERVER
SERVER_PORT: 8091
ACTIVE_PROFILE: dev

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: elkastaliotmane@gmail.com
EMAIL_PASSWORD: mkuxulrfcwmxrlpl
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
